index:
    path: /
    controller: App\Controller\DefaultController::index

login_register:
    path: /login_register
    controller: App\Controller\SecurityController::login_register

login_register2:
    path: /login_register2
    controller: App\Controller\SecurityController::login_register2

panier:
    path: /panier
    controller: App\Controller\DefaultController::panier